export const GET_ALL_RAW_DATA = "GET_ALL_RAW_DATA";
export const GET_SOCKET = "GET_SOCKET";

export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const GET_USER_STATISTICS = "GET_USER_STATISTICS";
export const PUSH_USER_STATISTICS = "PUSH_USER_STATISTICS";
export const PUSH_ACCURACY_FAQ = "PUSH_ACCURACY_FAQ";
export const PUSH_MOVEMENT_FAQ = "PUSH_ACCURACY_FAQ";